### ISSUE TITLE
1.12 bugs

### ISSUE THREAD

**Issue by Late-Night** [Voronoiii/BYG#20]
i know you said you're not taking 1.12 issues anymore, but there's 2 biggish bugs that need seen to imo
1. you cannot make charcoal with this mod's wood without using thermal expansion
2. saplings spawn their respective trees in weirdly(there's a diagonal displacement to their spawning behavior of about 2-3 blocks)

**Comment by Late-Night** [comment]
shouting at me is very unlikely to get me to listen to you
maybe try rewriting the mod for 1.12

**Comment by AOCAWOL** [comment]
I apologize for my partner's previous response. Before we did not have access to the BYG Mcreator Workspace but we do now. However, we will not be supporting this version anymore as from a modding standpoint it is much more difficult to rewrite and backport. Feel free to check out the beta 1.12.2 build (1.7.2) this still uses Mcreator as it is simply just the original workspace from it. I hope you reconsider at least giving the latest version a try as it is much more refined and has overall better quality than the mcreator versions of the mod. At this time we will not be backporting due to putting our resources into newer versions as the mod fits and incorporates better into the newer features and allows us to expand upon newer vanilla features such as villages, pillager outposts and utilizing newer vanilla blocks to help enhance the overall feeling of the biomes.

**Comment by Late-Night** [comment]
fine
i'll just delete the mod and get a better one
see ya never, you misbegotten shitfucks
