### ISSUE TITLE
There are some biomes that don't spawn because of Biomes O' Plenty.

### ISSUE THREAD

**Issue by DeadPigman17** [Voronoiii/BYG#27]
When choosing Biomes O' Plenty as the world type, all beach biomes and the tropical island biome (as far as I've tested) don't spawn. I've checked this by using Nature's Compass mod.

They do spawn when using BYG world type, but there are two other biome modss I'd like to play with, which are only compatible with BYG if I use Biomes O' Plenty world type.

**Comment by Voronoiii** [comment]
The reason for this is because of the biome layering system. If we had our islands/beaches spawning they'd spawn as actually biomes and not beaches or islands so this is an inconvenience and I'm sure BOP would not even think of adding support for our mod in their layering system. So this is out of our control unfortunately. Sorry for any inconvenience this may cause.

**Comment by DeadPigman17** [comment]
And is it possible that you could add compatibility with these 2 mods for the BYG world type? They are called Traverse: Legacy Continued and Project: Vibrant Journeys.

**Comment by Voronoiii** [comment]
In the next update it'll be available. We're redoing the world type so ye.

**Comment by DeadPigman17** [comment]
Oh ok, that's nice to hear.
